name: Build LineageOS for Redmi 12 5G

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install repo git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig openjdk-11-jdk -y

    - name: Initialize ROM repo
      run: |
        mkdir lineage
        cd lineage
        repo init -u https://github.com/VoltageOS/manifest.git -b 14

    - name: Sync sources
      run: |
        cd lineage
        repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

    - name: Clone device sources
      run: |
        cd lineage
        git clone https://github.com/<iamchochu>/<your-device-tree-repo>.git device/xiaomi/sky
        # Agar alag se vendor aur kernel tree hai to:
        # git clone <vendor-link> vendor/xiaomi/sky
        # git clone <kernel-link> kernel/xiaomi/sky

    - name: Start build
      run: |
        cd lineage
        source build/envsetup.sh
        lunch lineage_sky-userdebug
        mka bacon -j$(nproc --all)

    - name: Upload ROM
      uses: actions/upload-artifact@v3
      with:
        name: lineage_sky
        path: lineage/out/target/product/sky/*.zip
